In [ ]:
import numpy as np

In [ ]:
a = np.array([1,2,3,4])
b = np.array([10,20,30,40])
print(a,b)

In [ ]:
print(type(a))
type(b)

In [ ]:
print(a+b)
print(a-b)
print(a*b)

In [ ]:
#Creating a2D array
a2 = np.array([[1,2],[4,6]])
print(a2)

[[1 2]
 [4 6]]


In [ ]:
print(a2.shape)
print(a2.ndim)
print(a2.dtype)   #tell the dimension of element inside array

(2, 2)
2
int64


Creating a 3D Array

In [ ]:
a3 = np.array([[[1,2,3],[4,5,6]],
              [[12,13,14],[15,16,17]],
              [[10,11,19],[18,17,22]]
])
print(a3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[12 13 14]
  [15 16 17]]

 [[10 11 19]
  [18 17 22]]]


In [ ]:
np.arange(10)
np.arange(2,20)
np.arange(2,20,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
np.random.randint(1,11, size=(2,3,2))

array([[[10, 10],
        [10,  6],
        [ 4,  6]],

       [[ 2,  8],
        [ 2, 10],
        [ 2,  6]]], dtype=int32)

In [ ]:
x = np.array([[1,2,3],
              [4,5,6],
              [23,45,12]])
y = np.array([[23,56,89],
              [65,43,12],
              [34,23,10]])
print(x)
print(y)

[[ 1  2  3]
 [ 4  5  6]
 [23 45 12]]
[[23 56 89]
 [65 43 12]
 [34 23 10]]


In [ ]:
print(x+y)
print(x-y)
print(x*y)

[[24 58 92]
 [69 48 18]
 [57 68 22]]
[[-22 -54 -86]
 [-61 -38  -6]
 [-11  22   2]]
[[  23  112  267]
 [ 260  215   72]
 [ 782 1035  120]]


In [ ]:
#2 different method of multiplication of array
print(x @y)
np.dot(x,y)

[[ 255  211  143]
 [ 621  577  476]
 [3862 3499 2707]]


array([[ 255,  211,  143],
       [ 621,  577,  476],
       [3862, 3499, 2707]])

In [ ]:
x.prod()          #multiply the element of array

np.int64(8942400)

In [ ]:
x.mean()

In [ ]:
b = x.mean(axis = 0)          #column wise
print(b)

[ 9.33333333 17.33333333  7.        ]


In [ ]:
c = x.mean(axis = 1 )          #row wise
print(c)

[ 2.          5.         26.66666667]


In [ ]:
print(x.sum())
print(x.std())                 #standard daviation
print(x.var())                 #varience

101
13.562839573037447
183.9506172839506


In [ ]:
arr = np.array([1,2,3,4,56,6,7])
print(np.percentile(arr,50))
print(np.percentile(arr,25))

2.5


In [ ]:
arr2 = np.random.randint(11,1000, (4,4))
print(arr2)

[[938 732 756 354]
 [118 871 213 805]
 [343 456 903 634]
 [945 930  30 760]]


In [ ]:
print(arr2.reshape(2,8))
print("-"*7)
print(arr2.reshape(8,2))

[[938 732 756 354 118 871 213 805]
 [343 456 903 634 945 930  30 760]]
-------
[[938 732]
 [756 354]
 [118 871]
 [213 805]
 [343 456]
 [903 634]
 [945 930]
 [ 30 760]]
